# ================================ Test Code Generated by GPT =================================================
import uuid
import threading
from django.test import TransactionTestCase
from django.contrib.auth.models import User
from django.db import connection
from rest_framework import status
from rest_framework.test import APIClient

from wallets.models import Tenant, Customer, Wallet, Transaction, IdempotencyKey
from wallets.services import WalletService
from wallets.exceptions import (
    InsufficientFundsError,
    CrossTenantOperationError,
    WalletNotFoundError
)


class WalletAPITests(TransactionTestCase):
    """
    Complete test suite for Multi-Tenant Wallet API.
    Covers all critical requirements from the take-home PDF.
    """

    def setUp(self):
        self.client = APIClient()

        # ---------- Tenants ----------
        self.tenant_a = Tenant.objects.create(name="Tenant Alpha")
        self.tenant_b = Tenant.objects.create(name="Tenant Beta")

        # ---------- Users ----------
        self.user_a1 = User.objects.create_user(username="alice_a", password="pass123")
        self.user_a2 = User.objects.create_user(username="charlie_a", password="pass123")
        self.user_b  = User.objects.create_user(username="bob_b", password="pass123")

        # ---------- Customers ----------
        self.customer_a1 = Customer.objects.create(
            tenant=self.tenant_a, user=self.user_a1, email="alice@alpha.com"
        )
        self.customer_a2 = Customer.objects.create(
            tenant=self.tenant_a, user=self.user_a2, email="charlie@alpha.com"
        )
        self.customer_b = Customer.objects.create(
            tenant=self.tenant_b, user=self.user_b, email="bob@beta.com"
        )

        # ---------- Wallets ----------
        self.wallet_a1 = Wallet.objects.create(
            tenant=self.tenant_a, customer=self.customer_a1, currency="USD"
        )
        self.wallet_a2 = Wallet.objects.create(
            tenant=self.tenant_a, customer=self.customer_a2, currency="USD"
        )
        self.wallet_b = Wallet.objects.create(
            tenant=self.tenant_b, customer=self.customer_b, currency="USD"
        )

        # ---------- Common URLs ----------
        self.deposit_url  = f"/api/wallets/{self.wallet_a1.id}/deposit/"
        self.withdraw_url = f"/api/wallets/{self.wallet_a1.id}/withdraw/"
        self.transfer_url = f"/api/wallets/{self.wallet_a1.id}/transfer/"
        self.history_url  = f"/api/wallets/{self.wallet_a1.id}/history/"

    # =========================================================
    # 1. TENANT RESOLUTION (X-Tenant-ID + API Key)
    # =========================================================

    def test_request_with_x_tenant_id_works(self):
        response = self.client.get(
            "/api/wallets/",
            HTTP_X_TENANT_ID=str(self.tenant_a.id)
        )
        self.assertEqual(response.status_code, 200)

    def test_request_with_api_key_works(self):
        response = self.client.get(
            "/api/wallets/",
            HTTP_X_API_KEY=self.tenant_a.api_key
        )
        self.assertEqual(response.status_code, 200)

    def test_request_with_authorization_api_key_works(self):
        response = self.client.get(
            "/api/wallets/",
            HTTP_AUTHORIZATION=f"Api-Key {self.tenant_a.api_key}"
        )
        self.assertEqual(response.status_code, 200)

    def test_request_without_tenant_header_fails(self):
        response = self.client.get("/api/wallets/")
        self.assertEqual(response.status_code, 400)
        # Middleware returns pure JsonResponse, so use .json()
        self.assertIn("error", response.json())

    def test_invalid_api_key_fails(self):
        response = self.client.get(
            "/api/wallets/",
            HTTP_X_API_KEY="this-is-not-a-valid-key"
        )
        self.assertIn(response.status_code, [400, 401])

    # =========================================================
    # 2. CORE MONEY OPERATIONS
    # =========================================================

    def test_deposit_success(self):
        response = self.client.post(
            self.deposit_url,
            data={"amount": 5000},
            format="json",
            HTTP_X_TENANT_ID=str(self.tenant_a.id)
        )
        self.assertEqual(response.status_code, 201)
        self.wallet_a1.refresh_from_db()
        self.assertEqual(self.wallet_a1.balance, 5000)

    def test_withdraw_success(self):
        WalletService.deposit(self.tenant_a.id, self.wallet_a1.id, 10000)

        response = self.client.post(
            self.withdraw_url,
            data={"amount": 3000},
            format="json",
            HTTP_X_TENANT_ID=str(self.tenant_a.id)
        )
        self.assertEqual(response.status_code, 201)
        self.wallet_a1.refresh_from_db()
        self.assertEqual(self.wallet_a1.balance, 7000)

    def test_withdraw_insufficient_funds(self):
        WalletService.deposit(self.tenant_a.id, self.wallet_a1.id, 2000)

        response = self.client.post(
            self.withdraw_url,
            data={"amount": 5000},
            format="json",
            HTTP_X_TENANT_ID=str(self.tenant_a.id)
        )
        self.assertEqual(response.status_code, 400)

    def test_transfer_success(self):
        WalletService.deposit(self.tenant_a.id, self.wallet_a1.id, 10000)

        response = self.client.post(
            self.transfer_url,
            data={
                "to_wallet_id": str(self.wallet_a2.id),
                "amount": 4000
            },
            format="json",
            HTTP_X_TENANT_ID=str(self.tenant_a.id)
        )

        # Temporary debug
        if response.status_code != 200:
            print("Transfer failed!")
            print("Status:", response.status_code)
            print("Body  :", response.content.decode())
            self.assertEqual(response.status_code, 200)

            self.wallet_a1.refresh_from_db()
            self.wallet_a2.refresh_from_db()
            self.assertEqual(self.wallet_a1.balance, 6000)
            self.assertEqual(self.wallet_a2.balance, 4000)

    def test_transfer_same_wallet_fails(self):
        response = self.client.post(
            self.transfer_url,
            data={
                "to_wallet_id": str(self.wallet_a1.id),
                "amount": 100
            },
            format="json",
            HTTP_X_TENANT_ID=str(self.tenant_a.id)
        )
        self.assertEqual(response.status_code, 400)

    def test_transfer_cross_tenant_blocked(self):
        response = self.client.post(
            self.transfer_url,
            data={
                "to_wallet_id": str(self.wallet_b.id),
                "amount": 100
            },
            format="json",
            HTTP_X_TENANT_ID=str(self.tenant_a.id)
        )
        # Should be blocked either by serializer or service
        self.assertIn(response.status_code, [400, 403, 404])

    # =========================================================
    # 3. IDEMPOTENCY
    # =========================================================

    def test_duplicate_idempotency_key_returns_same_response(self):
        idem_key = str(uuid.uuid4())
        payload = {"amount": 2500}
        headers = {
            "HTTP_X_TENANT_ID": str(self.tenant_a.id),
            "HTTP_IDEMPOTENCY_KEY": idem_key
        }

        response1 = self.client.post(
            self.deposit_url, data=payload, format="json", **headers
        )
        self.assertEqual(response1.status_code, 201)

        response2 = self.client.post(
            self.deposit_url, data=payload, format="json", **headers
        )
        self.assertEqual(response2.status_code, 201)

        # Same response body → no double charge
        self.assertEqual(response1.json(), response2.json())

        # Only one transaction should exist
        self.assertEqual(
            Transaction.objects.filter(wallet=self.wallet_a1, type="DEPOSIT").count(),
            1
        )

    # =========================================================
    # 4. CONCURRENCY / RACE CONDITION
    # =========================================================

    def test_concurrent_transfers_prevent_double_spend(self):
        WalletService.deposit(self.tenant_a.id, self.wallet_a1.id, 10000)

        results = []
        payload = {"to_wallet_id": str(self.wallet_a2.id), "amount": 6000}

        def do_transfer():
            connection.close()
            client = APIClient()
            try:
                response = client.post(
                    self.transfer_url,
                    data=payload,
                    format="json",
                    HTTP_X_TENANT_ID=str(self.tenant_a.id)
                )
                results.append(response.status_code)
            except Exception as e:
                results.append(str(e))

        t1 = threading.Thread(target=do_transfer)
        t2 = threading.Thread(target=do_transfer)
        t1.start()
        t2.start()
        t1.join()
        t2.join()

        self.wallet_a1.refresh_from_db()
        # Balance should never go negative
        self.assertGreaterEqual(self.wallet_a1.balance, 0)
        # At most one transfer should have succeeded
        self.assertIn(self.wallet_a1.balance, [4000, 10000])

    # =========================================================
    # 5. TENANT ISOLATION
    # =========================================================

    def test_cross_tenant_wallet_access_blocked(self):
        # Try to deposit into tenant_b wallet while using tenant_a context
        url = f"/api/wallets/{self.wallet_b.id}/deposit/"
        response = self.client.post(
            url,
            data={"amount": 1000},
            format="json",
            HTTP_X_TENANT_ID=str(self.tenant_a.id)
        )
        self.assertEqual(response.status_code, 404)

    def test_cannot_see_other_tenant_wallets(self):
        response = self.client.get(
            "/api/wallets/",
            HTTP_X_TENANT_ID=str(self.tenant_a.id)
        )
        self.assertEqual(response.status_code, 200)
        wallet_ids = [str(w["id"]) for w in response.data]
        self.assertNotIn(str(self.wallet_b.id), wallet_ids)

    # =========================================================
    # 6. LEDGER & BALANCE
    # =========================================================

    def test_balance_is_calculated_from_ledger(self):
        WalletService.deposit(self.tenant_a.id, self.wallet_a1.id, 5000)
        WalletService.withdraw(self.tenant_a.id, self.wallet_a1.id, 1500)

        self.wallet_a1.refresh_from_db()
        self.assertEqual(self.wallet_a1.balance, 3500)

        # Verify actual ledger entries
        txs = Transaction.objects.filter(wallet=self.wallet_a1)
        self.assertEqual(txs.count(), 2)

    def test_wallet_history_returns_balance_and_transactions(self):
        WalletService.deposit(self.tenant_a.id, self.wallet_a1.id, 2000)

        response = self.client.get(
            self.history_url,
            HTTP_X_TENANT_ID=str(self.tenant_a.id)
        )
        self.assertEqual(response.status_code, 200)
        self.assertIn("live_balance", response.data)
        self.assertEqual(response.data["live_balance"], 2000)

    # =========================================================
    # 7. VALIDATION
    # =========================================================

    def test_deposit_negative_amount_fails(self):
        response = self.client.post(
            self.deposit_url,
            data={"amount": -100},
            format="json",
            HTTP_X_TENANT_ID=str(self.tenant_a.id)
        )
        self.assertEqual(response.status_code, 400)

    def test_deposit_zero_amount_fails(self):
        response = self.client.post(
            self.deposit_url,
            data={"amount": 0},
            format="json",
            HTTP_X_TENANT_ID=str(self.tenant_a.id)
        )
        self.assertEqual(response.status_code, 400)